apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moonagenttracker-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: moonagenttracker.com
      http:
        paths:
          - path: /agent
            pathType: Prefix
            backend:
              service:
                name: agent-service
                port:
                  number: 80
